name: Develop Development WorkFlow

on: # 이벤트 트리거
  push: # push event 트리거
    branches:
      - develop #develop 브랜치에서 push 이벤트가 일어났을 때 실행

jobs:
  build: 
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # Node 환경을 설정하여 npm 커맨드를 사용할 수 있도록 하는 Action을 불러옵니다.
    - uses: actions/setup-node@v2
      with:
        node-version: "14"

    tasks: 
      - name: npm install
        run: |
          npm install

      - name: npm build
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          npm run build

      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp
            --recursive
            --region ap-northeast-2
            build s3://u-life-kurly-frontend

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2

        # Cloud Front 무효화 설정
        - name: Invalidate 
        run: |
            aws cloudfront create-invalidation --distribution-id E29ZLV8ZCQND7S --paths '/*'
      

